
name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 
        
    - name: Test Functions
      run: |
        npm install axios
        node tests.js
